create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email varchar(255) not null unique,
  password_hash varchar(255) not null,
  created_at timestamptz not null default now(),
  is_active boolean not null default true
);

create table if not exists public.speeches (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  text text not null check (char_length(text) between 1 and 5000),
  language varchar(10) not null check (language in ('en', 'hi', 'es', 'fr', 'de')),
  voice varchar(80) not null default 'Standard',
  speed double precision not null default 1.0 check (speed between 0.5 and 2.0),
  pitch double precision not null default 1.0 check (pitch between 0.5 and 2.0),
  volume double precision not null default 1.0 check (volume between 0.0 and 1.0),
  audio_path varchar(1000) not null,
  created_at timestamptz not null default now()
);

create index if not exists speeches_user_created_idx on public.speeches(user_id, created_at desc);

insert into storage.buckets (id, name, public)
values ('audio', 'audio', true)
on conflict (id) do update set public = excluded.public;
